project:
  type: website

website:
  title: "DECIDE Case Studies"
  image: images/DECIDE_logo_RGB-1.png
  favicon: images/favicon.png
  twitter-card:
    site: "@decide_h2020"
  open-graph: true
  site-url: https://https://decideproject.eu/
  repo-url: https://github.com/decide-project-eu/case-studies-website
  repo-actions: [edit, issue]
  google-analytics: "G-2804FN9QRK"
  navbar:
    background: "#f0eeeb"
    logo: images/DECIDE_logo_RGB-1.png
    logo-alt: "Decide brand"
    title: false
    collapse-below: lg
    right:
      - case-studies/index.qmd
      - text: "Tutorials"
        menu: 
          - text: "Cattle barometer"
            href: https://public.tableau.com/views/Version4_16871894441320/Positivesamplerate?:language=en-US&:display_count=n&:origin=viz_share_link
      - text: "Network"
        menu: 
        - text: "overview"
          href: https://decideproject.eu/network/
        - text: "Partners"
          href: https://decideproject.eu/partners/
        - text: "Contact us"
          href: https://decideproject.eu/contact/
  sidebar: 
    - title: "About us"
      contents:
        - about-rwds.qmd
        - viewpoints/editors-blog/posts/2022/10/18/meet-the-team.qmd
        - rwds-partners.qmd
        - contact.qmd
        - ts-and-cs.qmd
    - title: "Call for contributions"
      contents:
        - contributor-docs/call-for-contributions.qmd
        - contributor-docs/case-studies.qmd
        - contributor-docs/explainers.qmd
        - contributor-docs/exercises.qmd
        - contributor-docs/datasets.qmd
        - contributor-docs/training-guides.qmd
        - contributor-docs/recommender.qmd
        - contributor-docs/datasciencebites.qmd
        - contributor-docs/contributor-guidelines.qmd
        - contributor-docs/style-guide.qmd
    - title: "Careers"
      contents:
        - careers/index.qmd
        - careers/career-profiles/index.qmd
    - title: "Ideas"
      contents:
        - ideas/index.qmd
        - ideas/tutorials/index.qmd
        - ideas/datasciencebites/index.qmd
    - title: "Viewpoints"
      contents: 
        - viewpoints/index.qmd
        - viewpoints/editors-blog/index.qmd
        - viewpoints/interviews/index.qmd
        - href: viewpoints/newsletter/index.qmd
          text: Newsletter

  page-navigation: true

  page-footer:
    background: "#000000"
    left: |
      Copyright &copy; 2023 [DECIDE PROJECT](https://https://decideproject.eu/)
    center:  
      - href: https://github.com/decide-project-eu/
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/decide_h2020
        icon: twitter
        aria-label: Twitter
      - href: https://www.linkedin.com/company/decide-h2020/
        icon: linkedin
        aria-label: LinkedIn
    right: |
      [Terms & Conditions](/ts-and-cs.qmd)

format:
  html:
    theme: [lux, decide.scss]
    css: decide.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto