project:
  type: website

website:
  title: "DECIDE Case Studies"
  image: images/DECIDE_logo_RGB-1.png
  favicon: images/favicon.png
  twitter-card:
    site: "@decide_h2020"
  open-graph: true
  site-url: https://github.com/decide-project-eu/case-studies-website
  repo-url: https://github.com/decide-project-eu/case-studies-website
  repo-actions: [edit, issue]
  google-analytics: "G-2804FN9QRK"
  navbar:
    background: "#f0eeeb"
    logo: images/DECIDE_logo_RGB-1.png
    logo-alt: "Decide brand"
    title: false
    collapse-below: lg
    right:
      - text: "Case studies"
        menu:
          - case-studies/cattle-barometer.qmd
          - case-studies/poultry-barometer.qmd
          - case-studies/pig-barometer.qmd
      - text: "Tutorials"
        menu:
          - tutorials/cattle-barometer.qmd
          - tutorials/anonymisation.qmd
          - tutorials/ontologies.qmd
          - tutorials/poultry-barometer.qmd
      - text: "Network"
        menu: 
        - text: "overview"
          href: https://decideproject.eu/network/
        - text: "Partners"
          href: https://decideproject.eu/partners/
        - text: "Contact us"
          href: https://decideproject.eu/contact/

  page-navigation: true

  page-footer:
    background: "#000000"
    left: |
      Copyright &copy; 2023 [DECIDE PROJECT](https://https://decideproject.eu/)
    center:  
      - href: https://github.com/decide-project-eu/
        icon: github
        aria-label: GitHub
      - href: https://twitter.com/decide_h2020
        icon: twitter
        aria-label: Twitter
      - href: https://www.linkedin.com/company/decide-h2020/
        icon: linkedin
        aria-label: LinkedIn
    right: |
      [Terms & Conditions](/ts-and-cs.qmd)

format:
  html:
    theme: [lux, decide.scss]
    css: decide.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto